config/routes.rb
Rails.application.routes.draw do
  

  resources :users
  resources :events

  root 'users#index'

  get 'event/suscribe/:event/:user', to: 'events#suscribe/'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
belongs_to :creator, class_name: "User"
has_and_belongs_to_many :attendees, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
has_many :created_events, class_name: "Event", foreign_key: "creator_id"
has_and_belongs_to_many :attended_events, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  @events = Event.all
  end

  def new
  @event = Event.new
  end

  def create
  @event = Event.new
	  @event.description = params_event[:description]
	  @event.date = params_event[:date]
	  @event.place = params_event[:place]
	  @event.creator = User.find(params_event[:creator_id])
	  if @event.save 
	  	redirect_to events_path
	  else 
	  	render 'new'
	  end
  end

  def show
    @event = Event.find(params[:id])
  end

  def suscribe
      
  end

    private
  def params_event
  	params.require(:event).permit(:description, :date, :place, :creator_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @users = User.all
  end

  def new
  @user = User.new
  end

  def create
	  @user = User.new
	  @user.name = params_user[:name]
	  if @user.save 
	  	redirect_to root_path
	  else 
	  	render 'new'
	  end
  end

  def show
    @user = User.find(params[:id])
  end


  private
  def params_user
  	params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Agenda</h1>

<table> <!-- on crée un tableau <!-->
  <tr>
    <th>Evenements</th>
    <th>Créateur</th>
  </tr>

<% @events.each do |event| %> <!-- pour chaque event : <!-->
<tr>
      <td><%= link_to event.description, event_path(event.id) %></td> <!-- on lui attribue sa description en passant par son id  <!-->
      <td><%= event.creator.name%></td> <!-- on affiche le nom de son créateur <!-->
   
</tr>
<%end%>
</table>

<%= link_to 'new', new_event_path %>

app/views/events/new.html.erb
<h1>Bienvenue !</h1>
<p>Ton évènement</p>

<%= form_for @event do |f| %>
  date: <%= f.date_field :date %><br />
  description: <%= f.text_area :description %><br />
  lieu: <%= f.text_field :place %><br />
  créateur: <%= f.collection_select(:creator_id, User.all, :id, :name) %>
  <%= f.submit %>
<% end %>

<%= link_to 'back', events_path %>

app/views/events/show.html.erb
<h1>Mon évènement</h1>

<h2><%= @event.creator.name%></h2>
<p><%= @event.description %></p>
<p><%= @event.date%></p>
<p><%= @event.place%></p>

<p><b>Participants</b></p>
<ul class="list-group"> <!-- on crée une liste <!-->
	<% @event.attendees.each do |user|%> <!-- pour chaque event crée par un user<!-->
		<li class="list-group-item"> <!-- on affiche une liste avec sa description et un lien <!-->
			<%= user.name%>
		</li>
	<%end%>
</ul>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Event-brite THP.</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= events_path %>">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">New Event</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_user_path %>">New User</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>
 
  	<body>
    <%= render "layouts/header" %>
    <div class="container" style="padding-top: 5rem;">
      <%= yield %>
    </div>
  </body>

</html>

app/views/users/index.html.erb
<h1>Listing</h1>
<p></p>

<table>
  <tr>
    <th>Utilisateurs</th>
    <th>Nombre d'évènements</th>
  </tr>

<% @users.each do |user| %>
<tr>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= user.created_events.count%></td>
</tr>
<%end%>
</table>

<%= link_to 'new', new_user_path %>

app/views/users/new.html.erb
<h1>Bienvenue !</h1>
<p>Inscris-toi</p>

<%= form_for @user do |f| %>
  nom: <%= f.text_field :name %><br />
  <%= f.submit %>
<% end %>

<%= link_to 'back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1> <!-- on met le nim du créateur en titre<!-->

<h2>Mes events</h2>

<ul class="list-group"> <!-- on crée une liste <!-->
	<% @user.created_events.each do |event| %> <!-- pour chaque event crée par un user<!-->
		<li class="list-group-item"> <!-- on affiche une liste avec sa description et un lien <!-->
			<%= event.description %>
			<%= link_to "(see more)", event_path(event.id) %> <!-- on crée un lien hypertexte qui redirige vers la page de l'event <!-->
		</li>
	<%end%>
</ul>
</br>
<h2>Mes participations</h2>

<ul class="list-group"> <!-- on crée une liste <!-->
	<% @user.attended_events.each do |event| %> <!-- pour chaque event crée par un user<!-->
		<li class="list-group-item"> <!-- on affiche une liste avec sa description et un lien <!-->
			<%= event.description %>
			<%= link_to "(see more)", event_path(event.id) %> <!-- on crée un lien hypertexte qui redirige vers la page de l'event <!-->
		</li>
	<%end%>
</ul>